### PR TITLE
Update core-doc-page.html

### PR DESCRIPTION
**Pull request by WTober**
this should be protocol relative: //fonts.google...

### CODE REVIEW

**Comment by ebidel** [comment]
Can you please sign the cla?

**Comment by WTober** [comment]
Hi Eric, 
Google said: It looks like you've already signed this CLA. If you'd like to edit your contact information, you may do so below.
Date Signed
Feb 14, 2015 13:49 PST
What can I do?

**Comment by WTober** [comment]
Ok, done!

**Comment by ebidel** [comment]
LGTM

**Pull request merged**
